"use strict"
/*
Even Fibonacci numbers

Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

const cache = [1, 2]
let sumOfEvens = BigInt(2),
    i = cache.length

while (true) {
    const value = cache[i - 1] + cache[i - 2]
    if (value > 4_000_000) break
    cache[i++] = value
    if (value % 2 === 0) sumOfEvens = sumOfEvens + BigInt(value)
}

console.log(sumOfEvens)
